import os
from typing import Any, Dict, List
from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain.chat_models import init_chat_model
from langchain.messages import ToolMessage, HumanMessage
from langchain.tools import tool
from langchain_pinecone import PineconeVectorStore
from langchain_openai import OpenAIEmbeddings

load_dotenv()

embeddings = OpenAIEmbeddings(
    model="text-embedding-3-small",
    show_progress_bar=False,
    chunk_size=50,
    retry_min_seconds=10,
)
print(os.environ["INDEX_NAME"])
vectorstore = PineconeVectorStore(
    index_name=os.environ["INDEX_NAME"], embedding=embeddings
)
model = init_chat_model(model="gpt-5.2", temperature=0, model_provider="openai")


@tool(response_format="content_and_artifact")
def retrieve_context(query: str):
    """
    Retrieve relevant documentation to help answer user queries about LangChain
    """
    # Retrieve documents from the vector store
    retrieve_docs = vectorstore.as_retriever().invoke(query, k=4)
    # Serialize the retrieved documents
    serialized_docs = "\n\n".join(
        (f"Source: {doc.metadata.get('source', 'unknown')}\n\n{doc.page_content}")
        for doc in retrieve_docs
    )
    return serialized_docs, retrieve_docs


def run_llm(query: str) -> Dict[str, Any]:
    """Run the RAG pipeline to answer a query using retrieved documentation.

    Args:
        query (str): The user's question

    Returns:
        Dict[str, Any]: containing:
            - answer (str): The final answer generated by the LLM.
            - sources (List[str]): List of sources used in the answer.
    """
    system_prompt = (
        "You are a helpful AI assistant that provides accurate information about LangChain. "
        "You have access to a tool that retrieves relevant documentation."
        " Use the retrieved documentation tool before answering the user's question."
        "Always cite the sources you used in your  answer."
        "If you cannot find the answer in the documentation, respond with 'I don't know.'"
    )
    agent = create_agent(
        model=model,
        tools=[retrieve_context],
        system_prompt=system_prompt,
    )
    # Create the initial messages list for the agent
    messages = [{"role": "user", "content": query}]
    # Invoke the agent with the messages
    response = agent.invoke({"messages": messages})
    # Extract the answer and sources from the response
    answer = response["messages"][-1].content
    # Extract context documents from ToolMessage artifacts
    context_docs = []
    for message in response["messages"]:
        # Check if this is a ToolMessage with artifact
        if isinstance(message, ToolMessage) and hasattr(message, "artifact"):
            print(message)
            # The artifact should contain the list of Document objects
            if isinstance(message.artifact, list):
                context_docs.extend(message.artifact)

    return {"answer": answer, "context": context_docs}


# if __name__ == "__main__":
#     result = run_llm(query="what are deep agents?")
#     print(result)
